/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V1RouteRouteImport } from './routes/v1/route'
import { Route as V2RouteRouteImport } from './routes/_v2/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1IndexRouteImport } from './routes/v1/index'
import { Route as V1VideoIndexRouteImport } from './routes/v1/video/index'
import { Route as V1NmixxIndexRouteImport } from './routes/v1/nmixx/index'
import { Route as V2TracksIndexRouteImport } from './routes/_v2/tracks/index'
import { Route as V1NmixxMemberRouteImport } from './routes/v1/nmixx/$member'

const V1RouteRoute = V1RouteRouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RouteRoute = V2RouteRouteImport.update({
  id: '/_v2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1IndexRoute = V1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V1RouteRoute,
} as any)
const V1VideoIndexRoute = V1VideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => V1RouteRoute,
} as any)
const V1NmixxIndexRoute = V1NmixxIndexRouteImport.update({
  id: '/nmixx/',
  path: '/nmixx/',
  getParentRoute: () => V1RouteRoute,
} as any)
const V2TracksIndexRoute = V2TracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => V2RouteRoute,
} as any)
const V1NmixxMemberRoute = V1NmixxMemberRouteImport.update({
  id: '/nmixx/$member',
  path: '/nmixx/$member',
  getParentRoute: () => V1RouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v1': typeof V1RouteRouteWithChildren
  '/v1/': typeof V1IndexRoute
  '/v1/nmixx/$member': typeof V1NmixxMemberRoute
  '/tracks/': typeof V2TracksIndexRoute
  '/v1/nmixx/': typeof V1NmixxIndexRoute
  '/v1/video/': typeof V1VideoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v1': typeof V1IndexRoute
  '/v1/nmixx/$member': typeof V1NmixxMemberRoute
  '/tracks': typeof V2TracksIndexRoute
  '/v1/nmixx': typeof V1NmixxIndexRoute
  '/v1/video': typeof V1VideoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_v2': typeof V2RouteRouteWithChildren
  '/v1': typeof V1RouteRouteWithChildren
  '/v1/': typeof V1IndexRoute
  '/v1/nmixx/$member': typeof V1NmixxMemberRoute
  '/_v2/tracks/': typeof V2TracksIndexRoute
  '/v1/nmixx/': typeof V1NmixxIndexRoute
  '/v1/video/': typeof V1VideoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/v1'
    | '/v1/'
    | '/v1/nmixx/$member'
    | '/tracks/'
    | '/v1/nmixx/'
    | '/v1/video/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/v1' | '/v1/nmixx/$member' | '/tracks' | '/v1/nmixx' | '/v1/video'
  id:
    | '__root__'
    | '/'
    | '/_v2'
    | '/v1'
    | '/v1/'
    | '/v1/nmixx/$member'
    | '/_v2/tracks/'
    | '/v1/nmixx/'
    | '/v1/video/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V2RouteRoute: typeof V2RouteRouteWithChildren
  V1RouteRoute: typeof V1RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v1': {
      id: '/v1'
      path: '/v1'
      fullPath: '/v1'
      preLoaderRoute: typeof V1RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_v2': {
      id: '/_v2'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof V2RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/': {
      id: '/v1/'
      path: '/'
      fullPath: '/v1/'
      preLoaderRoute: typeof V1IndexRouteImport
      parentRoute: typeof V1RouteRoute
    }
    '/v1/video/': {
      id: '/v1/video/'
      path: '/video'
      fullPath: '/v1/video/'
      preLoaderRoute: typeof V1VideoIndexRouteImport
      parentRoute: typeof V1RouteRoute
    }
    '/v1/nmixx/': {
      id: '/v1/nmixx/'
      path: '/nmixx'
      fullPath: '/v1/nmixx/'
      preLoaderRoute: typeof V1NmixxIndexRouteImport
      parentRoute: typeof V1RouteRoute
    }
    '/_v2/tracks/': {
      id: '/_v2/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof V2TracksIndexRouteImport
      parentRoute: typeof V2RouteRoute
    }
    '/v1/nmixx/$member': {
      id: '/v1/nmixx/$member'
      path: '/nmixx/$member'
      fullPath: '/v1/nmixx/$member'
      preLoaderRoute: typeof V1NmixxMemberRouteImport
      parentRoute: typeof V1RouteRoute
    }
  }
}

interface V2RouteRouteChildren {
  V2TracksIndexRoute: typeof V2TracksIndexRoute
}

const V2RouteRouteChildren: V2RouteRouteChildren = {
  V2TracksIndexRoute: V2TracksIndexRoute,
}

const V2RouteRouteWithChildren =
  V2RouteRoute._addFileChildren(V2RouteRouteChildren)

interface V1RouteRouteChildren {
  V1IndexRoute: typeof V1IndexRoute
  V1NmixxMemberRoute: typeof V1NmixxMemberRoute
  V1NmixxIndexRoute: typeof V1NmixxIndexRoute
  V1VideoIndexRoute: typeof V1VideoIndexRoute
}

const V1RouteRouteChildren: V1RouteRouteChildren = {
  V1IndexRoute: V1IndexRoute,
  V1NmixxMemberRoute: V1NmixxMemberRoute,
  V1NmixxIndexRoute: V1NmixxIndexRoute,
  V1VideoIndexRoute: V1VideoIndexRoute,
}

const V1RouteRouteWithChildren =
  V1RouteRoute._addFileChildren(V1RouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V2RouteRoute: V2RouteRouteWithChildren,
  V1RouteRoute: V1RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
