/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicVideoIndexRouteImport } from './routes/(public)/video/index'
import { Route as publicMusicIndexRouteImport } from './routes/(public)/music/index'
import { Route as publicAboutIndexRouteImport } from './routes/(public)/about/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicVideoIndexRoute = publicVideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicMusicIndexRoute = publicMusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutIndexRoute = publicAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/about': typeof publicAboutIndexRoute
  '/music': typeof publicMusicIndexRoute
  '/video': typeof publicVideoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/about': typeof publicAboutIndexRoute
  '/music': typeof publicMusicIndexRoute
  '/video': typeof publicVideoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(public)/about/': typeof publicAboutIndexRoute
  '/(public)/music/': typeof publicMusicIndexRoute
  '/(public)/video/': typeof publicVideoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/music' | '/video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/music' | '/video'
  id:
    | '__root__'
    | '/(public)'
    | '/(public)/'
    | '/(public)/about/'
    | '/(public)/music/'
    | '/(public)/video/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/video/': {
      id: '/(public)/video/'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof publicVideoIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/music/': {
      id: '/(public)/music/'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof publicMusicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about/': {
      id: '/(public)/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicAboutIndexRoute: typeof publicAboutIndexRoute
  publicMusicIndexRoute: typeof publicMusicIndexRoute
  publicVideoIndexRoute: typeof publicVideoIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicAboutIndexRoute: publicAboutIndexRoute,
  publicMusicIndexRoute: publicMusicIndexRoute,
  publicVideoIndexRoute: publicVideoIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
